version: "2"
plugins:
  rubocop:
    enabled: true
    channe: "rubocop-0-49"
    config:
      file: .rubocop.yml
  shellcheck:
    enabled: true
  eslint:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  # hlint:
  #   enabled: true
  markdownlint:
    enabled: true
  # git.legal:
  #   enabled: true
  scsslint:
    enabled: true
  # nodesecurity:
  #   enabled: true
exclude_patterns:
- config/
- db/
- public/api/docs/
