version: "2"
plugins:
  rubocop:
    enabled: true
    channe: "rubocop-0-70"
    config:
      file: .rubocop.yml
  haml-lint:
    enabled: true
  shellcheck:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  git.legal:
    enabled: true
  scsslint:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- config/
- db/
- public/api/docs/
