sudo: required
language: ruby
cache:
  bundler: true
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- nvm install 9.11.1
- nvm use 9.11.1
- "./bin/frontend-update.sh"
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id
  $CC_TEST_REPORTER_ID"
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: TZqifWTjUVoLnR81YSrpBsM0vIxFhrPpr/jJZbZ1cK6uIJU3VSw9U0FRSkxfuK+0/mb9PIfLFMVwJkTtyWZNbaEw3MJOU7nfOghnxHmjfDAzdD+yZxVK74pXz/m4rffYC0KEXtKNlL51D0tXo6zEDCPFOb4T+v1JWB0M8vKR/Abqoi3uSsOM2yug4t8ePtXoT9meamT5ZKafoswQjiGk8b3PkMH2K5H8mc25GR6sPJ2wpJrVQ8IhsRdhuk5NppTRah4Sok4CKq8BggYhj3qoVHaWUQAC1GP+3iMK3WdFZ/8Rl9vzNF25/UOoQI9wtuMTUQJxx2o8T9Mi8c+tjlFlwEIBQXvn18QQ5UAZTFIB04vockHpYWaUkNpxmPatFj/F67zss410pLdZdpsYNRsbpNRjwyspCDI1lgqGosE98YIjZSNY1hMlechAvorm1NcTBMipylpKgseeMFOZB9NOEMwEr3dKVmZM/WREw0iP237n27TuTpp/QTezxotQgS4xiDbeejDhrunLj/YC8vkSWHnWxeFqKcmnW9279J4d11p8I+4rbsk3HJhkzVNwrXKrVor5K0xXYE4RYbMq57YllTGpzBOEWDmDvXu889aTKBklG/VnSsb5lnfIoPCqEmtwFA8VghxToe+Jt8J76fLfUOoccG4r02nzNLDApYWrXD0=
  on:
    repo: ServiceInnovationLab/pancake-backend
  app:
    dev: pancakenz-staging
    master: pancakenz
  run:
  - bundle exec rake db:migrate
  - restart
env:
  global:
    secure: T7+npfKb6EW0G++OP4C91y2WMrMYyOrozeNT1WPCuedd5vKdILSskMz5LBav54F0J6OBbwozH82e0xclMTa23VuOrc9805tEcwtSRdDYb/mIb7F6gEyseqLIk/TZvDfmB5Yrrji0IVX9s5q0OKfVVb0rTrgh87pSRW2YnYAu41k6v2pK/OquixQX0sogblOLfKYprqh4h3Ay6+1IIDmC/lg0XSe+0xRFBZ5FJk0ycStu74xM+qbphIFgzd6q2kChFqRrOporeCgN3WSAFsQd7QneLITN3eucH9AR0OC9Udpuxr8tvAqTfy7Lo3ogj9PTYjD60ObQjcr212d/isSaZd6Zk2wHH35bzsZU3Y5f6vsILiZVJY2rDPkf7A6jMrWSPw8jd/CRizFjedveF9jCy3J2viwNI23y4Ce+sQkc5u0dAV3Z7n5Avy1R/UjyBpRoYb7VhfX1mZTKsVfLPoOxMuvChyOAL4MZGR83N9emHoLFL1r/JsRlqtun/F8i7vsu3OmqpO9ZcexEh+jx1Hqt6qSizNto6bQkKQ5WOul0kfT9U4kIHcKe0EIsUmD2d6CYLXBIYuSitp3/Fq/yX/tUwm9tJED+J0g76g8ItFAznf+7nYe4MSh039ehOKXLW4v+w6624RYfmjCauNHb4HSmwE0n2y8XgLwat7Tj1hwV8Qc=
