sudo: required
language: ruby
cache:
  bundler: true
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
script:
- bundle install
- yarn install
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id $CC_TEST_REPORTER_ID"
env:
  global:
  - PGPORT=5433
  - YEAR=2018
  - SIGNING_URL="http://127.0.0.1:4000/#/{token}"
  - OPENFISCA_ORIGN="https://govtnz-rates-rebate-of.herokuapp.com/" 
