#!/usr/bin/env bash

if ! [ $TRAVIS_PULL_REQUEST == "false" ]; then
  echo "This is a pull request. Skipping docker build and ECR deployment.";
  # exit 0;
fi

TAG=`if [ "$TRAVIS_BRANCH" == "dev" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
COMMIT=${TRAVIS_COMMIT::8}

echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
echo "TRAVIS_PULL_REQUEST = $TRAVIS_PULL_REQUEST"
echo "TAG = $TAG"
echo "COMMIT = $COMMIT"
echo "DOCKER_REPO = $DOCKER_REPO"
echo "DOCKER_ECR = $DOCKER_ECR"

docker --version
pip install --user awscli
export PATH=$PATH:$HOME/.local/bin

docker build -t $DOCKER_REPO .
docker tag $DOCKER_REPO $DOCKER_ECR/$DOCKER_REPO:$TAG

eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
docker push $DOCKER_ECR/$DOCKER_REPO:$TAG
