local:
  # service: Disk
  # root: <%= Rails.root.join("storage") %>
  service: S3
  bucket: <%= ENV["AMAZON_BUCKET"] %>
  access_key_id: <%= ENV["AMAZON_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AMAZON_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  bucket: <%= ENV["AMAZON_BUCKET"] %>
  access_key_id: <%= ENV["AMAZON_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AMAZON_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
